# Generated by Django 5.1.6 on 2025-04-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "log_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("action", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "audit_log",
            },
        ),
    ]
