# Generated by Django 5.1.6 on 2025-04-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notifications_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('module', models.CharField()),
                ('to_user_id', models.CharField()),
                ('message', models.CharField()),
                ('notifications_status', models.CharField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'admin.notifications',
            },
        ),
    ]
