# Generated by Django 5.1.6 on 2025-04-15 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="notification",
            table='admin"."notifications',
        ),
    ]
